build:
    script:
    - sed -i s/deb.debian.org/ftp.au.debian.org/g /etc/apt/sources.list
    - apt-get update
    - apt-get install -y build-essential xz-utils bc git wget
    - ./build-ci-wrapper.sh
    artifacts:
        paths:
            - build
        expire_in: 1 week
