build:
    image: registry.gitlab.com/matt_traverse/alpine-kernel-build-base:latest
    script:
    - ./build-ci-wrapper.sh
    artifacts:
        paths:
            - build
        expire_in: 1 week
